=== TechBond7/go-fintech/xsd/EFL_8300XBatchSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2018 (http://www.altova.com) by FinCEN (Department of the Treasury - Financial Crimes Enforcement Network) -->
<!-- current version v1.0-->
<!-- revision history: 
03/15/2019 (v1.0)-->
<xsd:schema xmlns="www.fincen.gov/base" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns:fc2="www.fincen.gov/base" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="www.fincen.gov/base" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1" xsi:schemaLocation="www.fincen.gov/base https://www.fincen.gov/sites/default/files/schema/base/BSA_XML_2.0.xsd">

	<!--Redefine START-->
		<xsd:complexType name="ActivityAssociationType">
					<xsd:sequence>
						<xsd:element name="CorrectsAmendsPriorReportIndicator" type="ValidateIndicatorType" minOccurs="0"/>
						<xsd:element name="InitialReportIndicator" type="ValidateIndicatorType" minOccurs="0"/>
					</xsd:sequence>
					<xsd:attribute name="SeqNum" type="xsd:long" use="required"/>
		</xsd:complexType>
		<xsd:complexType name="ActivityNarrativeInformationType">
					<xsd:sequence>
						<xsd:element name="ActivityNarrativeSequenceNumber" type="ValidateActivityNarrativeSequenceNumber"/>
						<xsd:element name="ActivityNarrativeText" type="RestrictString750"/>
					</xsd:sequence>
					<xsd:attribute name="SeqNum" type="xsd:long" use="required"/>
		</xsd:complexType>
		<xsd:complexType name="ActivityType">
					<xsd:sequence>
						<xsd:element name="EFilingPriorDocumentNumber" type="RestrictLong14" minOccurs="0"/>
						<xsd:element name="FilingDateText" type="DateYYYYMMDDType"/>
						<xsd:element name="MultipleSubjectsIndicator" type="ValidateIndicatorType" minOccurs="0"/>
						<xsd:element name="SuspiciousTransactionIndicator" type="ValidateIndicatorType" minOccurs="0"/>
						<xsd:element name="TransactionOnBehalfMultiplePersonsIndicator" type="ValidateIndicatorType" minOccurs="0"/>
					</xsd:sequence>
					<xsd:attribute name="SeqNum" type="xsd:long" use="required"/>
		</xsd:complexType>
		<xsd:complexType name="AddressType">
					<xsd:sequence>
						<xsd:element name="RawCityText" type="RestrictString50" minOccurs="0"/>
						<xsd:element name="RawCountryCodeText" type="RestrictString2" minOccurs="0"/>
						<xsd:element name="RawStateCodeText" type="RestrictString3" minOccurs="0"/>
						<xsd:element name="RawStreetAddress1Text" type="RestrictString100" minOccurs="0"/>
						<xsd:element name="RawZIPCode" type="RestrictString9" minOccurs="0"/>
					</xsd:sequence>
					<xsd:attribute name="SeqNum" type="xsd:long" use="required"/>
		</xsd:complexType>
		<xsd:complexType name="CurrencyTransactionActivityDetailType">
					<xsd:sequence>
						<xsd:element name="CurrencyTransactionActivityDetailTypeCode" type="ValidateCurrencyTransactionActvityDetailCodeType" minOccurs="0"/>
						<xsd:element name="DetailTransactionAmountText" type="RestrictString15" minOccurs="0"/>
						<xsd:element name="DetailTransactionDescription" type="xsd:string" minOccurs="0"/>
						<xsd:element name="InstrumentProductServiceTypeCode" type="ValidateInstrumentProductServiceTypeCode" minOccurs="0"/>
						<xsd:element name="IssuerNameText" type="xsd:string" minOccurs="0"/>
						<xsd:element name="OtherForeignCurrencyCountryText" type="RestrictString2" minOccurs="0"/>
					</xsd:sequence>
					<xsd:attribute name="SeqNum" type="xsd:long" use="required"/>
		</xsd:complexType>
		<xsd:complexType name="CurrencyTransactionActivityType">
					<xsd:sequence>
						<xsd:element name="InstallmentPaymentOtherIndicator" type="ValidateIndicatorType" minOccurs="0"/>
						<xsd:element name="Total100DollarBillInAmountText" type="xsd:string" minOccurs="0"/>
						<xsd:element name="TotalCashInReceiveAmountText" type="xsd:string"/>
						<xsd:element name="TotalPriceAmountText" type="xsd:string" minOccurs="0"/>
						<xsd:element name="TransactionDateText" type="DateYYYYMMDDType"/>
					</xsd:sequence>
					<xsd:attribute name="SeqNum" type="xsd:long" use="required"/>
		</xsd:complexType>
		<xsd:complexType name="PartyIdentificationType">
					<xsd:sequence>
						<xsd:element name="OtherIssuerStateText" type="RestrictString3" minOccurs="0"/>
						<xsd:element name="PartyIdentificationNumberText" type="RestrictString25" minOccurs="0"/>
						<xsd:element name="PartyIdentificationTypeCode" type="ValidatePartyIdentificationCodeType"/>
					</xsd:sequence>
					<xsd:attribute name="SeqNum" type="xsd:long" use="required"/>
		</xsd:complexType>
		<xsd:complexType name="PartyNameType">
					<xsd:sequence>
						<xsd:element name="PartyNameTypeCode" type="ValidatePartyNameCodeType" minOccurs="0"/>
						<xsd:element name="RawEntityIndividualLastName" type="RestrictString150" minOccurs="0"/>
						<xsd:element name="RawIndividualFirstName" type="RestrictString35" minOccurs="0"/>
						<xsd:element name="RawIndividualMiddleName" type="RestrictString35" minOccurs="0"/>
						<xsd:element name="RawIndividualTitleText" type="RestrictString35" minOccurs="0"/>
						<xsd:element name="RawPartyFullName" type="RestrictString150" minOccurs="0"/>
					</xsd:sequence>
					<xsd:attribute name="SeqNum" type="xsd:long" use="required"/>
		</xsd:complexType>
		<xsd:complexType name="PartyOccupationBusinessType">
					<xsd:sequence>
						<xsd:element name="OccupationBusinessText" type="RestrictString30"/>
					</xsd:sequence>
					<xsd:attribute name="SeqNum" type="xsd:long" use="required"/>
		</xsd:complexType>
		<xsd:complexType name="PartyType">
					<xsd:sequence>
						<xsd:element name="ActivityPartyTypeCode" type="ValidateActivityPartyCodeType"/>
						<xsd:element name="IndividualBirthDateText" type="DateYYYYMMDDOrBlankType" minOccurs="0"/>
						<xsd:element name="PartyTypeCode" type="ValidatePartyTypeCode" minOccurs="0"/>
					</xsd:sequence>
					<xsd:attribute name="SeqNum" type="xsd:long" use="required"/>
		</xsd:complexType>
		<xsd:complexType name="PhoneNumberType">
					<xsd:sequence>
						<xsd:element name="PhoneNumberText" type="RestrictString16"/>
					</xsd:sequence>
					<xsd:attribute name="SeqNum" type="xsd:long" use="required"/>
		</xsd:complexType>
	<!--Redefine END-->

	<!--Batch START-->
	<xsd:element name="EFilingBatchXML">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="FormTypeCode" type="xsd:string" fixed="8300X"/>
				<xsd:element ref="Activity" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="TotalAmount" type="xsd:decimal" use="required"/>
			<xsd:attribute name="PartyCount" type="xsd:long" use="required"/>
			<xsd:attribute name="ActivityCount" type="xsd:long" use="required"/>
		</xsd:complexType>
		<xsd:unique name="Unique-SeqNum">
			<xsd:selector xpath=".//*"/>
			<xsd:field xpath="@SeqNum"/>
		</xsd:unique>
	</xsd:element>
	<xsd:element name="Activity">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="ActivityType">
					<xsd:sequence>
						<xsd:element name="ActivityAssociation" type="ActivityAssociationType"/>
						<xsd:element ref="Party" minOccurs="4" maxOccurs="203"/>
						<xsd:element ref="CurrencyTransactionActivity"/>
						<xsd:element name="ActivityNarrativeInformation" type="ActivityNarrativeInformationType" minOccurs="0"/>
					</xsd:sequence>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Party">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="PartyType">
					<xsd:sequence>
						<xsd:element name="PartyName" type="PartyNameType" minOccurs="0" maxOccurs="2"/>
						<xsd:element name="Address" type="AddressType" minOccurs="0"/>
						<xsd:element name="PhoneNumber" type="PhoneNumberType" minOccurs="0"/>
						<xsd:element name="PartyIdentification" type="PartyIdentificationType" minOccurs="0" maxOccurs="3"/>
						<xsd:element name="PartyOccupationBusiness" type="PartyOccupationBusinessType" minOccurs="0"/>
					</xsd:sequence>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:unique name="Unique-PartyNameTypeCode">
			<xsd:selector xpath="fc2:PartyName"/>
			<xsd:field xpath="fc2:PartyNameTypeCode"/>
		</xsd:unique>
		<xsd:unique name="Unique-PartyIdentificationTypeCode">
			<xsd:selector xpath="fc2:PartyIdentification"/>
			<xsd:field xpath="fc2:PartyIdentificationTypeCode"/>
		</xsd:unique>
	</xsd:element>
	<xsd:element name="CurrencyTransactionActivity">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="CurrencyTransactionActivityType">
					<xsd:sequence>
						<xsd:element name="CurrencyTransactionActivityDetail" type="CurrencyTransactionActivityDetailType" minOccurs="2" maxOccurs="9"/>
					</xsd:sequence>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:unique name="Unique-CurrencyTransactionActivityDetailTypeCode">
			<xsd:selector xpath="fc2:CurrencyTransactionActivityDetail"/>
			<xsd:field xpath="fc2:CurrencyTransactionActivityDetailTypeCode"/>
		</xsd:unique>
		<xsd:unique name="Unique-InstrumentProductServiceTypeCode">
			<xsd:selector xpath="fc2:CurrencyTransactionActivityDetail"/>
			<xsd:field xpath="fc2:InstrumentProductServiceTypeCode"/>
		</xsd:unique>
	</xsd:element>
	<!--Batch END-->
	<!--Validation START-->
	<xsd:simpleType name="DateYYYYMMDDType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="(19|20)[0-9][0-9](0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[01])"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DateYYYYMMDDOrBlankType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="(19|20)[0-9][0-9](0[0-9]|1[0-2])(0[0-9]|1[0-9]|2[0-9]|3[01])|"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RestrictString2">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="2"/>
			<xsd:pattern value="\S+( +\S+)*|"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RestrictString3">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="3"/>
			<xsd:pattern value="\S+( +\S+)*|"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RestrictString9">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="9"/>
			<xsd:pattern value="\S+( +\S+)*|"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RestrictLong14">
		<xsd:restriction base="xsd:long">
			<xsd:totalDigits value="14"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RestrictString15">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="15"/>
			<xsd:pattern value="\S+( +\S+)*|"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RestrictString16">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="16"/>
			<xsd:pattern value="\S+( +\S+)*|"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RestrictString25">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
			<xsd:pattern value="\S+( +\S+)*|"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RestrictString30">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="30"/>
			<xsd:pattern value="\S+( +\S+)*|"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RestrictString35">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="35"/>
			<xsd:pattern value="\S+( +\S+)*|"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RestrictString50">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="50"/>
			<xsd:pattern value="\S+( +\S+)*|"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RestrictString100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
			<xsd:pattern value="\S+( +\S+)*|"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RestrictString150">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="150"/>
			<xsd:pattern value="\S+( +\S+)*|"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RestrictString750">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="750"/>
			<xsd:pattern value="\S+( +\S+)*|"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ValidateIndicatorType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Y"/>
			<xsd:enumeration value=""/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ValidateActivityPartyCodeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="35">
				<xsd:annotation>
					<xsd:documentation>Transmitter</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="37">
				<xsd:annotation>
					<xsd:documentation>Transmitter Contact</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="16">
				<xsd:annotation>
					<xsd:documentation>Individual from whom the cash was received</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="23">
				<xsd:annotation>
					<xsd:documentation>Person on whose behalf transaction conducted</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="4">
				<xsd:annotation>
					<xsd:documentation>Business that received cash</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="8">
				<xsd:annotation>
					<xsd:documentation>Contact for assistance</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="3">
				<xsd:annotation>
					<xsd:documentation>Authorized Official</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ValidatePartyNameCodeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="L">
				<xsd:annotation>
					<xsd:documentation>Legal name</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="DBA">
				<xsd:annotation>
					<xsd:documentation>Doing business as (DBA)</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ValidatePartyTypeCode">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="I">
				<xsd:annotation>
					<xsd:documentation>Individual</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="O">
				<xsd:annotation>
					<xsd:documentation>Organization</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="U">
				<xsd:annotation>
					<xsd:documentation>Unknown</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ValidateInstrumentProductServiceTypeCode">
		<xsd:restriction base="xsd:int">
			<xsd:enumeration value="35">
				<xsd:annotation>
					<xsd:documentation>U.S. Currency</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="16">
				<xsd:annotation>
					<xsd:documentation>Foreign Currency</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="39">
				<xsd:annotation>
					<xsd:documentation>Cashier's Check(s)</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="26">
				<xsd:annotation>
					<xsd:documentation>Money Order(s)</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="40">
				<xsd:annotation>
					<xsd:documentation>Bank Draft(s)</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="34">
				<xsd:annotation>
					<xsd:documentation>Traveler's Check(s)</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ValidatePartyIdentificationCodeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="1">
				<xsd:annotation>
					<xsd:documentation>SSN/ITIN</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="2">
				<xsd:annotation>
					<xsd:documentation>EIN</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="5">
				<xsd:annotation>
					<xsd:documentation>Driver's license/State ID</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="6">
				<xsd:annotation>
					<xsd:documentation>Passport</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="7">
				<xsd:annotation>
					<xsd:documentation>Alien registration</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="28">
				<xsd:annotation>
					<xsd:documentation>Transmitter Control Code</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="999">
				<xsd:annotation>
					<xsd:documentation>Other</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ValidateCurrencyTransactionActvityDetailCodeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="1">
				<xsd:annotation>
					<xsd:documentation>Personal property purchased</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="2">
				<xsd:annotation>
					<xsd:documentation>Real property purchased</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="3">
				<xsd:annotation>
					<xsd:documentation>Personal services provided</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="4">
				<xsd:annotation>
					<xsd:documentation>Business services provided</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="5">
				<xsd:annotation>
					<xsd:documentation>Intangible property purchased</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="6">
				<xsd:annotation>
					<xsd:documentation>Debt obligations paid</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="7">
				<xsd:annotation>
					<xsd:documentation>Exchange of cash</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="8">
				<xsd:annotation>
					<xsd:documentation>Escrow or trust funds</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="9">
				<xsd:annotation>
					<xsd:documentation>Bail received by clerks</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="999">
				<xsd:annotation>
					<xsd:documentation>Other</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ValidateActivityNarrativeSequenceNumber">
		<xsd:restriction base="xsd:int">
			<xsd:enumeration value="1">
				<xsd:annotation>
					<xsd:documentation>The value must equal 1</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<!--Validation END-->
</xsd:schema>

=== TechBond7/go-fintech/data/samples/doep_batch.xml
<EFilingBatchXML ActivityCount="1" PartyCount="2" SeqNum="1"
                     xsi:schemaLocation="www.fincen.gov/base https://www.fincen.gov/base https://www.fincen.gov/base/EFL_8300XBatchSchema.xsd"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xmlns:fc2="www.fincen.gov/base">
    <Activity SeqNum="1">
        <Party SeqNum="2">
            <ActivityPartyTypeCode>35</ActivityPartyTypeCode>
            <PartyName SeqNum="5">
                <PartyNameTypeCode>L</PartyNameTypeCode>
                <RawPartyFullName>Transmitter legal name</RawPartyFullName>
            </PartyName>
            <Address SeqNum="6">
                <RawCityText>Transmitter city</RawCityText>
                <RawCountryCodeText>US</RawCountryCodeText>
                <RawStateCodeText>VA</RawStateCodeText>
                <RawStreetAddress1Text>Transmitter street address</RawStreetAddress1Text>
                <RawZIPCode>22113</RawZIPCode>
            </Address>
            <PhoneNumber SeqNum="7">
                <PhoneNumberText>7217894455</PhoneNumberText>
            </PhoneNumber>
            <PartyIdentification SeqNum="8">
                <PartyIdentificationNumberText>458985215</PartyIdentificationNumberText>
                <PartyIdentificationTypeCode>2</PartyIdentificationTypeCode>
            </PartyIdentification>
        </Party>
        <Party SeqNum="9">
            <ActivityPartyTypeCode>37</ActivityPartyTypeCode>
            <PartyName SeqNum="11">
                <PartyNameTypeCode>L</PartyNameTypeCode>
                <RawPartyFullName>Transmitter contact legal name</RawPartyFullName>
            </PartyName>
        </Party>
        <Party SeqNum="12">
            <ActivityPartyTypeCode>11</ActivityPartyTypeCode>
            <PartyAsEntityOrganizationIndicator>Y</PartyAsEntityOrganizationIndicator>
            <PartyName SeqNum="13">
                <PartyNameTypeCode>L</PartyNameTypeCode>
                <RawEntityIndividualLastName>Johnson Wedding Company</RawEntityIndividualLastName>
            </PartyName>
            <PartyName SeqNum="14">
                <PartyNameTypeCode>DBA</PartyNameTypeCode>
                <RawPartyFullName>JWC</RawPartyFullName>
            </PartyName>
            <Address SeqNum="15">
                <RawCityText>Rockcreek</RawCityText>
                <RawStateCodeText>NY</RawStateCodeText>
                <RawStreetAddress1Text>987 Flint Street</RawStreetAddress1Text>
                <RawZIPCode>21121</RawZIPCode>
            </Address>
            <PhoneNumber SeqNum="16">
                <PhoneNumberExtensionText>4412</PhoneNumberExtensionText>
                <PhoneNumberText>3659855214</PhoneNumberText>
            </PhoneNumber>
            <PartyIdentification SeqNum="17">
                <PartyIdentificationNumberText>212121211</PartyIdentificationNumberText>
                <PartyIdentificationTypeCode>2</PartyIdentificationTypeCode>
            </PartyIdentification>
            <PartyOccupationBusiness SeqNum="18">
                <NAICSCode>554</NAICSCode>
                <OccupationBusinessText>Wedding Planner</OccupationBusinessText>
            </PartyOccupationBusiness>
            <ElectronicAddress SeqNum="19">
                <ElectronicAddressText>johnson@wedding.org</ElectronicAddressText>
            </ElectronicAddress>
        </Party>
        <Party SeqNum="20">
            <ActivityPartyTypeCode>45</ActivityPartyTypeCode>
            <PrimaryRegulatorTypeCode>1</PrimaryRegulatorTypeCode>
            <PartyName SeqNum="21">
                <RawPartyFullName>Bank of the West</RawPartyFullName>
            </PartyName>
            <Address SeqNum="22">
                <RawCityText>Cityville</RawCityText>
                <RawStateCodeText>AZ</RawStateCodeText>
                <RawStreetAddress1Text>555 Rolling Creek Way</RawStreetAddress1Text>
                <RawZIPCode>554478985</RawZIPCode>
            </Address>
            <PartyIdentification SeqNum="23">
                <PartyIdentificationNumberText>318181818</PartyIdentificationNumberText>
                <PartyIdentificationTypeCode>2</PartyIdentificationTypeCode>
            </PartyIdentification>
            <PartyIdentification SeqNum="24">
                <PartyIdentificationNumberText>445581258</PartyIdentificationNumberText>
                <PartyIdentificationTypeCode>14</PartyIdentificationTypeCode>
            </PartyIdentification>
        </Party>
        <FilingDateText>19801025</FilingDateText>
        <ActivityAssociation SeqNum="25">
            <InitialDesignationIndicator>Y</InitialDesignationIndicator>
        </ActivityAssociation>
        <DesignationExemptActivity SeqNum="26">
            <ExemptBasisTypeCode>C</ExemptBasisTypeCode>
            <ExemptEffectiveBeginDateText>20190208</ExemptEffectiveBeginDateText>
        </DesignationExemptActivity>
    </Activity>
    <FormTypeCode>DOEPX</FormTypeCode>
</EFilingBatchXML>
